[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
